GET http://localhost:3000/api/users HTTP/1.1

###

POST  http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json 

{
    "firstname": "Jane",
    "lastname": "DOE",
    "age": 23
}

###

PUT  http://localhost:3000/api/users/2 HTTP/1.1
Content-Type: application/json 

{
    "firstname": "Axel",
    "lastname": "DOE",
    "age": 23
}


###

DELETE   http://localhost:3000/api/users/1 HTTP/1.1

