GET http://localhost:3000/api/users HTTP/1.1

###

POST  http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json 

{
    "firstname": "Koffi",
    "lastname": "Aron",
    "age": 23
}

###

PUT  http://localhost:3000/api/users/6 HTTP/1.1
Content-Type: application/json 

{
    "firstname": "Koffi",
    "lastname": "Salima",
    "age": 23
}


###

DELETE   http://localhost:3000/api/users/7 HTTP/1.1


###

GET http://localhost:3000/api/notifications HTTP/1.1

